/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import modelovani.Day;
import modelovani.Logic;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author On
 */
public class Panel extends javax.swing.JFrame {
    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }
    
    private int tcount = 0;
    int experimentId=1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pocet_lidi = new javax.swing.JSlider();
        startButton = new javax.swing.JButton();
        graphPanel = new javax.swing.JPanel();
        numberOfAccidents = new javax.swing.JLabel();
        numberOfAccidentsUDI = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pocet_lidi.setMaximum(20);
        pocet_lidi.setToolTipText("");
        pocet_lidi.setValue(10);
        pocet_lidi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pocet_lidiMouseDragged(evt);
            }
        });
        pocet_lidi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pocet_lidiMouseReleased(evt);
            }
        });

        startButton.setText("Spustit");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        graphPanel.setBackground(new java.awt.Color(255, 255, 255));
        graphPanel.setLayout(new java.awt.BorderLayout());

        numberOfAccidents.setText("Celkový počet nehod: 0");

        numberOfAccidentsUDI.setText("Celkový počet pod vlivem: 0");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Počet aktorů", "Počet nehod", "Počet nehod al."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pocet_lidi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfAccidents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberOfAccidentsUDI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(numberOfAccidents)
                            .addGap(6, 6, 6)
                            .addComponent(numberOfAccidentsUDI))
                        .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pocet_lidi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
       Logic logic = new Logic(pocet_lidi.getValue()/10.0, this,experimentId);
       this.tcount += 1;
       this.experimentId++;
    }//GEN-LAST:event_startButtonActionPerformed

    private void pocet_lidiMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pocet_lidiMouseDragged
        Double number = new Double(pocet_lidi.getValue()/10.0);
        //labelPocetLidi.setText(number.toString()+" X");
    }//GEN-LAST:event_pocet_lidiMouseDragged

    private void pocet_lidiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pocet_lidiMouseReleased
       Double number = new Double(pocet_lidi.getValue()/10.0);
       //labelPocetLidi.setText(number.toString()+" X");
    }//GEN-LAST:event_pocet_lidiMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }
    
    
     public void graph(Day [] days) {
         int actors=0;
         int accidents=0;
        
         
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        for (int i = 0; i <= 31; i++) { 
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Leden");
        dataset.setValue(accidents, "Počet nehod","Leden");
        actors=0;
        accidents=0;
        for (int i = 31; i < 60; i++) { 
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Únor");
        dataset.setValue(accidents, "Počet nehod","Únor");
        actors=0;
        accidents=0;
        for (int i = 60; i < 91; i++) {    
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Březen");
        dataset.setValue(accidents, "Počet nehod","Březen");
        actors=0;
        accidents=0;
        for (int i = 91; i < 121; i++) {    
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Duben");
        dataset.setValue(accidents, "Počet nehod","Duben");
        actors=0;
        accidents=0;
        for (int i = 121; i < 152; i++) { 
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Květen");
        dataset.setValue(accidents, "Počet nehod","Květen");
        actors=0;
        accidents=0;
        for (int i = 152; i < 182; i++) { 
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Červen");
        dataset.setValue(accidents, "Počet nehod","Červen");
        actors=0;
        accidents=0;
        for (int i = 182; i < 213; i++) {    
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Červenec");
        dataset.setValue(accidents, "Počet nehod","Červenec");
        actors=0;
        accidents=0;
        for (int i = 213; i < 244; i++) {   
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Srpen");
        dataset.setValue(accidents, "Počet nehod","Srpen");
        actors=0;
        accidents=0;
        for (int i = 244; i < 274; i++) {  
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Září");
        dataset.setValue(accidents, "Počet nehod","Září");
        actors=0;
        accidents=0;
        for (int i = 274; i < 305; i++) {  
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Říjen");
        dataset.setValue(accidents, "Počet nehod","Říjen");
        actors=0;
        accidents=0;
        for (int i = 305; i < 335; i++) {    
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Listopad");
        dataset.setValue(accidents, "Počet nehod","Listopad");
        actors=0;
        accidents=0;
        for (int i = 335; i < 365; i++) {  
            actors=actors + days[i].actors;
            accidents=accidents + days[i].accidents;
         }
        dataset.setValue(actors, "Počet lidí","Prosinec");
        dataset.setValue(accidents, "Počet nehod","Prosinec");
        actors=0;
        accidents=0;
        
        JFreeChart chart = ChartFactory.createBarChart("Poměr počtu lidí a nehod za daný měsíc", "Měsíc", "Počet lidí", dataset, PlotOrientation.VERTICAL, true, true, true);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartPanel chartPanel = new ChartPanel(chart);
        graphPanel.removeAll();
        graphPanel.add(chartPanel, BorderLayout.CENTER);
        graphPanel.validate();
       
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        int n = 0, uid = 0, a = 0;
        for(Day d: days){
            n += d.accidents;
            uid += d.uid;
            a += d.actors;
        }
        
        numberOfAccidents.setText("Celkový počet nehod: " + n);
        numberOfAccidentsUDI.setText("Celkový počet pod vlivem: " + uid);
        
        Object[] row = { this.tcount, a, n, uid };
        model.addRow(row);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel numberOfAccidents;
    private javax.swing.JLabel numberOfAccidentsUDI;
    private javax.swing.JSlider pocet_lidi;
    private javax.swing.JButton startButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
